sudo: required

language: python

services:
  - docker

python:
  - "3.6"

addons:
  hosts:
    - hs2.example.com
    - nn.example.com

branches:
  only:
  - master

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

install:
  - pip install -r requirements.txt

env:
  - DOCKER_COMPOSE_VERSION=1.23.0 DOCKER_CLIENT_TIMEOUT=180 COMPOSE_HTTP_TIMEOUT=180

script:
  - docker-compose -version
  - docker version
  - bash tests/run_tests_travis.sh
  - bash run_tests.sh -s
  - travis_wait 20 bash run_tests.sh -t
